### ISSUE TITLE
Binding doesn't work in nested views

### ISSUE THREAD

**Issue by thorseye** [Infviz/Orange#2]
Having the following html-structure, bindings for the child-view doesn't work

``` html
<div data-view="UI.ParentView">
  <div data-view="UI.ChildView"></div>
</div>
```

**Comment by markusjohnsson** [comment]
I assume the nested div is actually the template of UI.ParentView?

After discussion with @jonatannyberg:

First of all, this is a knockout-specific problem. While we both need and want to support knockout, I think it is sound to keep the core of Orange free from a knockout dependency. 

ViewBase, right now a part of SampleApplication, should probably be separated into ViewBase and KnockoutViewBase, where only KnockoutViewBase depends on knockout. Also, KnockoutViewBase should not call `ko.applyBindings` in its constructor, instead it should be called when a view model property is set.

Further, there are at least two cases to consider here:

### 1. You have a foreach binding which create sub-views dynamically

``` html
<!-- ParentView template -->
<div data-bind="foreach: items">
  <div data-view="UI.ChildView"></div>
</div>
```

In this case, `ChildView` should probably not make a call to `ko.applyBindings` (which the current `ViewBase` constructor does), but instead let binding context flow from `ParentView`. This means that you won't inject the `ChildViewModel` into the constructor of the `ChildView`.

Also, the `data-view` mechanism dynamically injects the ChildView HTML code without knockout's knowledge, which means that bindings will not work until we find a way to trigger a knockout update of the HTML. Perhaps something like: `<div data-bind="view: 'UI.ChildView"></div>` might be easier to get working. 

### 2.  You have truly independent views, with independent viewmodels

And the ChildViewModel is constructor-injected to the view. In this case, you need to use knockout's `stopBinding`-binding:

``` html
<!-- ParentView template -->
<div data-bind="stopBinding: true">
  <div data-view="UI.ChildView"></div>
</div>
```

The binding context from `ParentView` will not propagate to the `ChildView`, but that also means that you cannot access the parent binding context. But you shouldn't need to, if the views are independent. This case should work with the current `ViewBase`, but you need to use `stopBinding: true`.

**Comment by markusjohnsson** [comment]
2cec37fc72 contains the "orange-vm" knockout extension. It works like the knockout "with" binding but it also sets the dataContext of the View-object.

``` javascript
    ko.applyBindings({ subViewModel: { someProperty: 'hey!' }});
```

``` html
    <div data-view="MainView">
         <div data-view="SubView" data-bind="orange-vm: subViewModel">
         </div>
    </div>
```
