### ISSUE TITLE
ControlManager tries to clean nodes that has not yet been created

### ISSUE THREAD

**Issue by markusjohnsson** [Infviz/Orange#7]
In some cases, ControlManager's cleaning mechanism runs before controls are actually created, causing it to crash.

```
<div data-bind="with: subViewModel">
    <div data-view="MyView"> 
    </div>
</div>
```

If subViewModel is null from start, knockout will remove the MyView div from the DOM before ControlManager has created a control for it. ControlManager will fire its mutationobserver handler and crash. It should check if there is an actual control instead of checking for data-view/data-control attributes.

**Comment by jonatannyberg** [comment]
This issue should no longer exist.
